# Generated by Django 5.0.6 on 2024-06-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Austria', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
