# Generated by Django 3.2 on 2024-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
