# Generated by Django 3.2 on 2024-06-19 11:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('music', 'Music'), ('nature', 'Nature'), ('animals', 'Animals'), ('city', 'City Life')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_1080p_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360p_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos_uploaded/original'),
            preserve_default=False,
        ),
    ]
