# Generated by Django 3.2 on 2024-06-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20240619_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_1080p_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720p_path',
        ),
    ]
