# Generated by Django 5.0.6 on 2024-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_480',
            field=models.FileField(blank=True, null=True, upload_to='videos_480p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos_720p'),
        ),
    ]
