# Generated by Django 5.0.6 on 2024-06-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_video_480_video_video_720p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_720p',
            new_name='video_720',
        ),
    ]
