# Generated by Django 5.0.6 on 2024-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_video_720p_video_video_720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_480',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/videos_480p'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_720',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/videos_720p'),
        ),
    ]
