# Generated by Django 5.0.6 on 2024-06-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_video_video_480_alter_video_video_720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_480',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720',
        ),
    ]
