# Generated by Django 5.0.6 on 2024-06-12 17:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_video_thumbnail_video_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('music', 'Music'), ('nature', 'Nature'), ('animals', 'Animals')], default=1, max_length=200),
        ),
    ]
