# Generated by Django 5.0.6 on 2024-06-12 20:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('music', 'Music'), ('nature', 'Nature'), ('animals', 'Animals'), ('city', 'City Life')], max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
